# Makefile fragment for the oem option. The generator wraps this in ifeq ($(WITH_OEM),true).
#
# Every rule is wildcard-guarded, so a build where nothing was extracted is a no-op rather than an
# error. That matters: the extractor only runs during bootstrap's sync phase, and these used to be
# hand-written into each device tree with the same guards, three times over.

# System sounds -> /system/media/audio, preserving the ringtones/notifications/alarms layout.
forge_oem_sounds := $(wildcard vendor/extra/oem-assets/sounds/media/audio/*/*.ogg)
PRODUCT_COPY_FILES += $(foreach f,$(forge_oem_sounds),\
    $(f):$(TARGET_COPY_OUT_SYSTEM)/media/audio/$(patsubst vendor/extra/oem-assets/sounds/media/audio/%,%,$(f)))

# system/media/audio belongs to generic_system.mk, which from Android 17 enforces that ownership:
# a device makefile adding files there fails the build (artifact_path_requirements.mk) unless they
# are named as allowed. Reclaimed sounds are exactly that case. Harmless on older branches, which
# have the same variable and simply never check it.
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += \
    system/media/audio/alarms/% \
    system/media/audio/notifications/% \
    system/media/audio/ringtones/% \
    system/media/audio/ui/%

# Wallpapers -> /product/media/wallpaper as raw files, plus the Backgrounds picker entries that make
# them selectable. Without the overlay they ship but cannot be chosen.
forge_oem_wallpaper := $(wildcard vendor/extra/oem-assets/wallpaper/*.png)
PRODUCT_COPY_FILES += $(foreach f,$(forge_oem_wallpaper),\
    $(f):$(TARGET_COPY_OUT_PRODUCT)/media/wallpaper/$(notdir $(f)))
DEVICE_PACKAGE_OVERLAYS += vendor/extra/overlay/oem-assets

# Backgrounds must be a STATIC overlay, not an RRO. A device that sets
# PRODUCT_ENFORCE_RRO_TARGETS (msm8996 sets it to *) turns every device overlay into a runtime
# overlay, and an RRO can only override a resource that already exists: it cannot add one. The
# partner_wallpapers array is overridden fine, so the picker is told about wallpapers it cannot
# resolve, and it silently renders nothing. The overlay does ship the images; what it cannot do is
# make them resolvable by name in the target package, because the idmap only maps names the target
# already defines. Measured on a vs995 build: the RRO carried the 17 entry array AND all 12
# drawables, while the base Backgrounds.apk had none of them, so every lookup returned 0.
#
# Only this one package is excluded. The framework overlays beside it (audio_assets, the
# SettingsProvider defaults) override resources that already exist, which is exactly what an RRO
# does correctly, so they stay runtime overlays and the device keeps a generic framework-res.
PRODUCT_ENFORCE_RRO_EXCLUDED_OVERLAYS += vendor/extra/overlay/oem-assets/packages/apps/Backgrounds

# Boot animation. TARGET_BOOTANIMATION is read later by vendor/lineage/bootanimation/Android.mk,
# which falls back to the generated one when it is empty -- so an absent zip needs no conditional.
# It is not a product variable, but a plain assignment here does reach that far: verified by setting
# it from this file and reading it back with get_build_var.
forge_oem_bootanim := $(wildcard vendor/extra/oem-assets/bootanimation.zip)
ifneq ($(forge_oem_bootanim),)
TARGET_BOOTANIMATION := $(forge_oem_bootanim)
endif

# The pack-specific half: which sound is the default ringtone, whether the pack has a home scene.
# Generated by whichever extractor ran, because the option cannot know a manufacturer's filenames.
-include vendor/extra/oem-assets/assets.mk
