#!/usr/bin/env python3
"""gen-tool-index.py — regenerate the tool index from the tools themselves.

  gen-tool-index.py            # rewrite docs/TOOLS.md and docs/tools.yaml
  gen-tool-index.py --check    # exit 1 if either is stale, change nothing

WHY IT IS GENERATED AND NOT WRITTEN

A hand-maintained index lists the tools that existed when someone last remembered to update it.
This one is derived from the tools, so a new tool appears the moment it exists and a deleted one
disappears. --check makes that enforceable rather than hopeful, and propagate-forge.sh runs it, so
an engine change cannot reach the device repos with an index that lies.

WHERE EACH FIELD COMES FROM

  name     the filename
  summary  line 2 onwards, which by convention reads "# <name> — <what it does>", joined across
           wrapped lines and cut at the first sentence
  usage    the first indented invocation line in the header block
  docs     any docs/*.md that mentions the tool by filename. A reverse scan, so writing about a
           tool in a doc is enough to link it here and nothing is declared twice.

Python rather than shell because the headers are UTF-8 prose and the summaries wrap. A first
attempt in sed under LC_ALL=C turned every em dash into replacement characters and cut each summary
at the first line break.
"""
import glob
import os
import re
import sys

FORGE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASHES = "—–-"


def decomment(line):
    line = re.sub(r'^#[ ]?', '', line)
    line = re.sub(r'^"""', '', line)
    line = re.sub(r"^'''", '', line)
    return line


def scan():
    rows = []
    paths = sorted(glob.glob('tools/**/*.sh', recursive=True) +
                   glob.glob('tools/**/*.py', recursive=True))
    for path in paths:
        base = os.path.basename(path)
        with open(path, encoding='utf-8', errors='replace') as fh:
            lines = fh.read().split('\n')

        # summary: line 2 plus wrapped continuation, to the first blank comment line
        chunk = []
        for ln in lines[1:8]:
            if not (ln.startswith('#') or ln.startswith('"""') or ln.startswith("'''")):
                break
            text = decomment(ln).strip()
            if not text:
                break
            chunk.append(text)
        summary = ' '.join(chunk)
        summary = re.sub(r'^' + re.escape(base) + r'\s*[' + DASHES + r']+\s*', '', summary)
        # Cut at a full stop only. Cutting at a colon too left descriptions ending in the colon
        # that was about to introduce the useful half -- "apply the composed customization stack
        # onto a synced LineageOS tree:" and nothing after it.
        sentence = re.match(r'(.+?\.)(\s|$)', summary)
        if sentence and len(sentence.group(1)) > 25:
            summary = sentence.group(1)
        summary = summary.rstrip(' .') or '(no description)'

        # usage: first indented invocation line naming the tool
        usage = base
        for ln in lines[1:40]:
            text = decomment(ln)
            # Headers spell the invocation several ways: bare, ./tools/x, ./forge/tools/x.
            # Accept any leading path, or 28 tools silently show their own name as their usage.
            if re.match(r'^ {2,}(?:\./)?(?:[\w.-]+/)*' + re.escape(base) + r'\b', text):
                usage = text.strip()
                break

        # The generated index is itself a docs/*.md that names every tool, so without this every
        # row would "link to further reading" that is the index it appears in.
        GENERATED = {'docs/TOOLS.md', 'docs/tools.yaml'}
        docs = []
        for d in sorted(set(glob.glob('docs/*.md')) - GENERATED):
            with open(d, encoding='utf-8', errors='replace') as fh:
                if base in fh.read():
                    docs.append(d)
        rows.append((base, path, summary, usage, docs))
    return rows


def render_md(rows):
    out = ["# Tool index", ""]
    out += ["**Generated by `tools/gen-tool-index.py`. Do not edit.** Re-run it after adding a tool,",
            "or run it with `--check` to find out whether this file is stale. `propagate-forge.sh`",
            "does that automatically, so an engine change cannot ship with an index that lies.", ""]
    out += ["%d tools. Each row is `| name | what it does | usage | docs |` with a fixed column count"
            % len(rows),
            "and any literal pipe escaped, so `awk -F'|'` is enough to parse it. `docs/tools.yaml`",
            "carries the same data for anything that would rather not parse Markdown.", ""]
    out += ["| tool | what it does | usage | further reading |", "|---|---|---|---|"]
    for base, path, summary, usage, docs in rows:
        links = ', '.join('[%s](%s)' % (os.path.basename(d)[:-3], os.path.basename(d))
                          for d in docs) or '—'
        out.append('| [`%s`](../%s) | %s | `%s` | %s |'
                   % (base, path, summary.replace('|', r'\|'),
                      usage.replace('|', r'\|'), links))
    return '\n'.join(out) + '\n'


def render_yaml(rows):
    def q(text):
        return text.replace('\\', '\\\\').replace('"', '\\"')
    out = ["# Generated by tools/gen-tool-index.py. Do not edit.",
           "# Same data as TOOLS.md, for anything that would rather not parse Markdown.",
           "count: %d" % len(rows), "tools:"]
    for base, path, summary, usage, docs in rows:
        out.append('  - name: "%s"' % q(base))
        out.append('    path: "%s"' % q(path))
        out.append('    summary: "%s"' % q(summary))
        out.append('    usage: "%s"' % q(usage))
        if docs:
            out.append('    docs:')
            out += ['      - "%s"' % q(d) for d in docs]
        else:
            out.append('    docs: []')
    return '\n'.join(out) + '\n'


def unrunnable():
    """Scripts that present themselves as commands but cannot be run.

    A shebang says "execute me"; without the mode bit, following any doc that names the script gives
    Permission denied. Three tools shipped that way before this check existed, so it is a recurring
    mistake rather than a one-off. Repo-wide, not just tools/: prebuilt/ and docker/ carry runnable
    scripts too, and the index only ever scanned tools/, which is how a fetcher nobody could list
    stayed invisible.

    A library that is meant to be sourced is exempt, and says so in its own header -- lib/presets.sh
    "Sourced; defines functions, runs nothing", prebuilt/lib-app-checks.sh "Source it; then:". That
    beats guessing from the path: tools/freestanding-arm64.sh is sourced too and lives in tools/.
    """
    bad = []
    for path in sorted(glob.glob('**/*.sh', recursive=True) + glob.glob('**/*.py', recursive=True)):
        if path.startswith(('templates/', '.git/')):
            continue        # templates carry @PLACEHOLDER@s and are instantiated, never run in place
        with open(path, encoding='utf-8', errors='replace') as fh:
            head = [next(fh, '') for _ in range(12)]
        if not head[0].startswith('#!'):
            continue        # no shebang: not claiming to be a command
        if any(re.search(r'\bsourced?\b', ln, re.I) for ln in head[1:]):
            continue        # declares itself a sourced library
        if not os.access(path, os.X_OK):
            bad.append(path)
    return bad


def main():
    os.chdir(FORGE)
    check = '--check' in sys.argv[1:]
    if '-h' in sys.argv[1:] or '--help' in sys.argv[1:]:
        print(__doc__.strip())
        return 0

    rows = scan()
    want = {'docs/TOOLS.md': render_md(rows), 'docs/tools.yaml': render_yaml(rows)}

    if check:
        stale = []
        for path, text in want.items():
            try:
                with open(path, encoding='utf-8') as fh:
                    if fh.read() != text:
                        stale.append(path)
            except FileNotFoundError:
                stale.append(path)
        if stale:
            for p in stale:
                print("!! %s is out of date" % p)
            print("   run tools/gen-tool-index.py to regenerate")
            return 1
        # The generated files cannot drift, but tools/README.md is hand-written and silently does:
        # six tools were missing from its Quick reference before this check existed. A tool nobody can
        # find is a tool nobody uses, so an unlisted one fails the check rather than passing as a nit.
        missing = []
        try:
            with open('tools/README.md', encoding='utf-8') as fh:
                readme = fh.read()
        except FileNotFoundError:
            readme = None
        if readme is not None:
            missing = [base for base, _p, _s, _u, _d in rows if base not in readme]
        if missing:
            for m in missing:
                print("!! %s is not listed in tools/README.md" % m)
            print("   add a row to its Quick reference table, or the tool is undiscoverable")
            return 1
        notx = unrunnable()
        if notx:
            for n in notx:
                print("!! %s has a shebang but is not executable" % n)
            print("   chmod +x it, or say in its header that it is sourced")
            return 1
        print(">> tool index is current (%d tools), every tool is listed in tools/README.md,"
              " and every script with a shebang is executable" % len(rows))
        return 0

    os.makedirs('docs', exist_ok=True)
    for path, text in want.items():
        with open(path, 'w', encoding='utf-8') as fh:
            fh.write(text)
    print(">> wrote docs/TOOLS.md and docs/tools.yaml (%d tools)" % len(rows))
    return 0


if __name__ == '__main__':
    sys.exit(main())
